CREATE SCHEMA IF NOT EXISTS JACTOR;

CREATE SEQUENCE hibernate_sequence
  START WITH 1000000
  INCREMENT BY 1;

CREATE TABLE T_ADDRESS (
  ID             BIGINT (19) DEFAULT hibernate_sequence.nextval PRIMARY KEY,
  CREATION_TIME  TIMESTAMP   NOT NULL,
  CREATED_BY     VARCHAR(50) NOT NULL,
  UPDATED_TIME   TIMESTAMP   NOT NULL,
  UPDATED_BY     VARCHAR(50) NOT NULL,
  ADDRESS_LINE_1 VARCHAR(50) NOT NULL,
  ADDRESS_LINE_2 VARCHAR(50),
  ADDRESS_LINE_3 VARCHAR(50),
  CITY           VARCHAR(50) NOT NULL,
  COUNTRY        VARCHAR(7),
  ZIP_CODE       INTEGER (4) NOT NULL,

  PRIMARY KEY (ID)
);
