CREATE TABLE T_ADDRESS (
  ID             BIGINT PRIMARY KEY,
  CREATION_TIME  TIMESTAMP   NOT NULL,
  CREATED_BY     VARCHAR(50) NOT NULL,
  UPDATED_TIME   TIMESTAMP   NOT NULL,
  UPDATED_BY     VARCHAR(50) NOT NULL,
  ADDRESS_LINE_1 VARCHAR(50) NOT NULL,
  ADDRESS_LINE_2 VARCHAR(50),
  ADDRESS_LINE_3 VARCHAR(50),
  CITY           VARCHAR(50) NOT NULL,
  COUNTRY        VARCHAR(7),
  ZIP_CODE       INTEGER (4) NOT NULL
);
