CREATE TABLE T_USER (
  ID             BIGINT PRIMARY KEY,
  CREATION_TIME  TIMESTAMP   NOT NULL,
  CREATED_BY     VARCHAR(50) NOT NULL,
  UPDATED_TIME   TIMESTAMP   NOT NULL,
  UPDATED_BY     VARCHAR(50) NOT NULL,
  EMAIL          VARCHAR(50),
  USER_NAME      VARCHAR(50) NOT NULL,
  PERSON_ID      BIGINT      NOT NULL,
  INACTIVE       BOOLEAN     NOT NULL,
  INACTIVE_SINCE DATE
);

ALTER TABLE T_USER
  ADD CONSTRAINT unique_user_name UNIQUE (USER_NAME);

ALTER TABLE T_USER
  ADD CONSTRAINT fk_u_person_id FOREIGN KEY (PERSON_ID)
REFERENCES T_PERSON (ID);
