package nu.hjemme.module.exception;

/**
 * Exception to use when encapsulate an exception which is generated by a third party component.
 * @author Tor Egil Jacobsen
 */
public class UnknownException extends CommonsException {
    private static final long serialVersionUID = 969237013119323861L;

    /**
     * Initializes a new exception with the cause of another exception.
     * @param cause The cause which caused the exception.
     */
    public UnknownException(final Throwable cause) {
        super(cause);
    }

    /**
     * Initializes a new exception with a message and a cause for the exception.
     * @param message The message.
     * @param cause The cause.
     */
    public UnknownException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
