CREATE TABLE T_PERSON (
  ID            BIGINT(19) PRIMARY KEY,
  CREATION_TIME TIMESTAMP   NOT NULL,
  CREATED_BY    VARCHAR(50) NOT NULL,
  UPDATED_TIME  TIMESTAMP   NOT NULL,
  UPDATED_BY    VARCHAR(50) NOT NULL,
  DESCRIPTION   VARCHAR(256),
  FIRST_NAME    VARCHAR(50),
  SURNAME       VARCHAR(50) NOT NULL,
  LOCALE        VARCHAR(10),
  USER_ID       BIGINT(19),
  ADDRESS_ID    BIGINT(19)  NOT NULL
);

ALTER TABLE T_PERSON
  ADD CONSTRAINT fk_p_address_id FOREIGN KEY (ADDRESS_ID)
REFERENCES T_ADDRESS (ID);
