CREATE SEQUENCE blog_entry_seq
  START WITH 10000000
  INCREMENT BY 1;

CREATE TABLE T_BLOG_ENTRY (
  ID            BIGINT(19) DEFAULT blog_entry_seq.nextval PRIMARY KEY,
  CREATION_TIME TIMESTAMP     NOT NULL,
  CREATED_BY    VARCHAR(50)   NOT NULL,
  UPDATED_TIME  TIMESTAMP     NOT NULL,
  UPDATED_BY    VARCHAR(50)   NOT NULL,
  CREATED_TIME  VARCHAR(50)   NOT NULL,
  CREATOR_NAME  VARCHAR(50)   NOT NULL,
  ENTRY         VARCHAR(2048) NOT NULL,
  BLOG_ID       BIGINT(19)    NOT NULL
);

ALTER TABLE T_BLOG_ENTRY
  ADD CONSTRAINT fk_be_blog_id FOREIGN KEY (BLOG_ID)
REFERENCES T_BLOG (ID);
