CREATE SEQUENCE guest_book_seq
  START WITH 10000000
  INCREMENT BY 1;

CREATE TABLE T_GUEST_BOOK (
  ID            BIGINT(19) DEFAULT guest_book_seq.nextval PRIMARY KEY,
  CREATION_TIME TIMESTAMP   NOT NULL,
  CREATED_BY    VARCHAR(50) NOT NULL,
  UPDATED_TIME  TIMESTAMP   NOT NULL,
  UPDATED_BY    VARCHAR(50) NOT NULL,
  TITLE         VARCHAR(50) NOT NULL,
  USER_ID       BIGINT(19)  NOT NULL
);

ALTER TABLE T_GUEST_BOOK
  ADD CONSTRAINT fk_gb_user_id FOREIGN KEY (USER_ID)
REFERENCES T_USER (ID);
