# funksjoner
function wcgrep {													# fun: del av funksjonen wcgrep
    grep -R $1 * | grep -v target | grep -v .svn | grep -v "~" | grep -v ".pyc" | grep -v Binary | grep --color -n $1	# fun: del av funksjonen wcgrep
}															# fun: del av funksjonen wcgrep


# System variables
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home	# var: miljøvariabel for filsti til gjeldende javaversjon
export PATH=/opt/subversion/bin/:$PATH						# var: miljøvariabel for systemets filstier
export WAR=hjemme.war								# var: miljøvariabel for navn på web archive for hjemme
export WS=$HOME/ws									# var: miljøvariabel for filsti til workspace

# Alias, navigering
alias cd..='cd ..'									# navigasjon: navigering ned en folder
alias cli='cd $WS/hjemme/hjemme-client'						# navigasjon: hjemme-client
alias fac='cd $WS/hjemme/hjemme-facade'						# navigasjon: hjemme-facade
alias hje='cd $WS/hjemme'								# navigasjon: hjemme
alias pom='cd $WS/hjemme-pom'							# navigasjon: hjemme-pom
alias mod='cd $WS/hjemme/hjemme-module'						# navigasjon: hjemme-module
alias tst='cd $WS/hjemme/hjemme-test'						# navigasjon: hjemme-test
alias web='cd $WS/hjemme-web/'							# navigasjon: hjemme-web
alias ws='cd $WS'									# navigasjon: workspace

# Alias, maven
alias mcc='mvn clean compile'							# cmd: mvn clean compile
alias mci='mvn clean install'							# cmd: mvn clean install
alias mct='mvn clean test'								# cmd: mvn clean tes
alias mcis='mvn clean install -DskipTests'						# cmd: mvn clean install -DskipTests
alias mcp='mvn clean package'							# cmd: mvn clean package
alias mct='mvn clean test'								# cmd: mvn clean test
alias mda='mvn dependency:analyze'							# cmd: mvn dependency:analyze
alias mdt='mvn dependency:tree'							# cmd: mvn dependency:tree
alias mhe='mvn help:effective-pom'							# cmd: mvn help:effective-pom
alias mvd='mvn versions:display-property-updates'					# cmd: mvn versions:display-property-updates

# Alias, diverse:
alias cmd='more $HOME/.bash_profile | grep.more'					# cmd: liste alle kommandoer, variabler og funksjoner i .bash_profile
alias grep='grep --color -n'								# cmd: grep med farger og linjenummer
alias grep.more='grep -e "# cmd:" -e "# div:" -e "# fun:" -e "# var:"'		# cmd: grep som filtrerer diverse strenger med som starter med # og slutter med :
alias la='ls -all -G'								# cmd: vis filer og mapper med farger
alias nav='more $HOME/.bash_profile | grep "# navigasjon:"'				# cmd: vis navigasjoner i .bash_profile
alias nav.til='nav | grep'								# cmd: oppgi tekststreng for å se om mulig navigasjon er lagt inn
alias rm.dir='rm -r -f'								# cmd: slett mapper rekursivt
