function wcgrep {															# funksjon
    grep -R $1 * | grep -v target | grep -v .svn | grep -v "~" | grep -v ".pyc" | grep -v Binary | grep --color $1			# funksjon
}																	# funksjon

# System variables
export WAR=hjemme.war										# var
export WS=/cygdrive/c/ws									# var

# Alias, navigering
alias cli='cd $WS/hjemme/hjemme-client'								# navigasjon
alias fac='cd $WS/hjemme/hjemme-facade'								# navigasjon
alias hje='cd $WS/hjemme'									# navigasjon
alias pom='cd $WS/hjemme-pom'									# navigasjon
alias mod='cd $WS/hjemme/hjemme-module'								# navigasjon
alias old='cd $WS/old.components'								# navigasjon
alias tes='cd $WS/hjemme/hjemme-test'								# navigasjon
alias web='cd $WS/hjemme-web/'									# navigasjon
alias ws='cd $WS'										# navigasjon

# Alias, maven
alias mcc='mvn clean compile'									# cmd
alias mci='mvn clean install'									# cmd
alias mcis='mvn clean install -DskipTests'							# cmd
alias mcp='mvn clean package'									# cmd
alias mct='mvn clean test'									# cmd
alias mda='mvn dependency:analyze'								# cmd
alias mdt='mvn dependency:tree'									# cmd
alias mdt.det='mdt | grep.no.down | grep.no.succ | grep.tree'					# cmd
alias mhe='mvn help:effective-pom'								# cmd
alias mvd='mvn versions:display-property-updates'						# cmd

# Alias, diverse:
alias cd..='cd ..'
alias cmd='more $HOME/.bashrc | grep.cmd'							# cmd: list alle alias for kommandoer i .bashrc
alias fun='more $HOME/.bashrc | grep -v fun= | grep "# funksjon"'				# cmd: list alle funksjonser (de som har kommentarene 'funksjon...') i .bashrc
alias grep.cmd='grep -e "# cmd" -e "# var"'							# cmd: grep etter kommandoer og variabler i .bashrc
alias grep='grep --color'									# cmd: filtrer paa ord (farglegg treff)
alias grep.nav='grep "# navigasjon"'								# cmd: grep etter alle kommendoer som inneholder en navigasjon
alias grep.no.down='grep -i -v "downloading" | grep -i -v "downloaded"'				# cmd: grep alt utenom "downloading" og "downloaded"
alias grep.no.succ='grep -v "SUCCESS"'								# cmd: grep alt utenom "SUCCESS"
alias grep.tree='grep -e "SNAPSHOT" -e "+" -e "|" -e "-" -e "no.spk.pensjon"'			# cmd: strenger som har interessant verdi ifm mvn dependency:tree
alias la='ls -la -hF --color=tty'								# cmd: list alt innhold i mapper med farger.
alias nav='more $HOME/.bashrc | grep -v "grep.nav" | grep.nav'					# cmd: list alle alias i .bashrc som har kommentar om navigasjon
alias nav.til='nav | grep'									# cmd: oppgi tekststreng til mulig navigasjon
alias rm.dir='rm -r -f'										# cmd: rekursiv fjerning av mapper med innhold
